/// 应用文案多语言表. key 统一 snake_case; 缺失时 L10n.t 回退简体中文.
///
/// 语言码: zh-CN 简体中文, zh-TW 繁体, en 英语, ja 日语, ko 韩语,
/// es 西班牙语, pt 葡萄牙语, hi 印地语.
///
/// 结构: 核心公共文案在本文件; 各页面翻译在 i18n/ 下按页分文件,
/// 通过 [_pageTables] 合并, 避免多人并行改同一文件冲突.
library;

import 'i18n/pages_group1.dart' as g1;
import 'i18n/pages_group2.dart' as g2;
import 'i18n/pages_group3.dart' as g3;
import 'i18n/pages_group4.dart' as g4;

class McStrings {
  static Map<String, String> of(String code) => _tables[code] ?? _zhCN;

  static final Map<String, Map<String, String>> _tables = {
    'zh-CN': _zhCN,
    'zh-TW': _zhTW,
    'en': _en,
    'ja': _ja,
    'ko': _ko,
    'es': _es,
    'pt': _pt,
    'hi': _hi,
  };

  /// 各分组页面翻译 (key → 8 语言). 由 i18n/pages_groupN.dart 提供.
  static final List<Map<String, Map<String, String>>> _groups = [
    g1.table, g2.table, g3.table, g4.table,
  ];

  /// 查找: 先查各页面分组, 再查本文件核心表.
  static String? lookup(String code, String key) {
    for (final g in _groups) {
      final byLang = g[key];
      if (byLang != null) {
        final v = byLang[code] ?? byLang['zh-CN'];
        if (v != null) return v;
      }
    }
    return of(code)[key];
  }

  // ---------------- 简体中文 (基准) ----------------
  static const Map<String, String> _zhCN = {
    'app_name': '明策',
    'nav_home': '首页',
    'nav_news': '资讯',
    'nav_chat': '聊天',
    'nav_mine': '我的',
    'user_center': '用户中心',
    'tab_profile': '个人资料',
    'tab_security': '安全设置',
    'tab_preference': '偏好设置',
    'change_avatar_hint': '点击更换头像',
    'nickname': '昵称',
    'username': '用户名',
    'email': '邮箱',
    'logout': '退出登录',
    'logout_confirm': '退出后聊天记录将保留在本机, 可随时重新登录.',
    'cancel': '取消',
    'save': '保存',
    'confirm': '确定',
    'exit': '退出',
    'edit_nickname': '修改昵称',
    'nickname_hint': '输入昵称, 留空则显示用户名',
    'avatar_updated': '头像已更新',
    'avatar_too_large': '图片超过 10MB',
    'avatar_upload_failed': '头像上传失败',
    'nickname_updated': '昵称已更新',
    'update_failed': '修改失败',
    'coming_soon': '该功能即将上线',
    // 安全设置
    'sec_account': '账号安全',
    'sec_login_password': '登录密码',
    'sec_fund_password': '资金密码',
    'sec_2fa': '谷歌验证 (2FA)',
    'sec_device_verify': '设备与验证',
    'sec_email_verify': '邮箱验证',
    'sec_phone_verify': '手机验证',
    'sec_devices': '登录设备管理',
    'sec_anti_phishing': '防钓鱼码',
    'status_set': '已设置',
    'status_unset': '未设置',
    'status_bound': '已绑定',
    'status_unbound': '未绑定',
    // 改登录密码
    'cp_title': '修改登录密码',
    'cp_old': '原密码',
    'cp_new': '新密码 (至少 8 位)',
    'cp_confirm': '确认新密码',
    'cp_submit': '确认修改',
    'cp_err_mismatch': '两次输入的新密码不一致',
    'cp_err_short': '新密码至少 8 位',
    'cp_done': '密码修改成功',
    // 偏好设置
    'pref_general': '通用',
    'pref_language': '语言',
    'pref_currency': '计价货币',
    'pref_price_color': '涨跌配色',
    'pref_notify': '通知',
    'pref_notify_market': '行情提醒',
    'pref_notify_notice': '公告推送',
    'color_green_up': '绿涨红跌',
    'color_red_up': '红涨绿跌',
    'enabled': '已开启',
    'disabled': '已关闭',
    'language_select': '选择语言',
    // 资讯
    'news': '资讯',
    'flash': '快讯',
    'notice': '公告',
    // 首页顶部 tab
    'home_tab_overview': '综合',
    'home_tab_market': '行情',
    'home_tab_terminal': '多维指数',
    'home_tab_liquidation': '多空爆仓',
    'home_tab_whale': '巨鲸雷达',
    'home_tab_funding': '资金费率',
    // main 全局
    'invite_recognized': '已识别邀请人, 注册时将自动填写邀请码',
    'friend_request_body': '{name} 请求添加你为好友',
    'view': '查看',
    'peer_default': '对方',
    'login_gate_title': '登录后使用{name}',
    'login_gate_sub': '终端功能需要验证身份',
    'go_login': '去登录',
  };

  // ---------------- 繁体中文 ----------------
  static const Map<String, String> _zhTW = {
    'app_name': '明策',
    'nav_home': '首頁',
    'nav_news': '資訊',
    'nav_chat': '聊天',
    'nav_mine': '我的',
    'user_center': '用戶中心',
    'tab_profile': '個人資料',
    'tab_security': '安全設置',
    'tab_preference': '偏好設置',
    'change_avatar_hint': '點擊更換頭像',
    'nickname': '暱稱',
    'username': '用戶名',
    'email': '郵箱',
    'logout': '退出登錄',
    'logout_confirm': '退出後聊天記錄將保留在本機, 可隨時重新登錄.',
    'cancel': '取消',
    'save': '保存',
    'confirm': '確定',
    'exit': '退出',
    'edit_nickname': '修改暱稱',
    'nickname_hint': '輸入暱稱, 留空則顯示用戶名',
    'avatar_updated': '頭像已更新',
    'avatar_too_large': '圖片超過 10MB',
    'avatar_upload_failed': '頭像上傳失敗',
    'nickname_updated': '暱稱已更新',
    'update_failed': '修改失敗',
    'coming_soon': '該功能即將上線',
    'sec_account': '賬號安全',
    'sec_login_password': '登錄密碼',
    'sec_fund_password': '資金密碼',
    'sec_2fa': '谷歌驗證 (2FA)',
    'sec_device_verify': '設備與驗證',
    'sec_email_verify': '郵箱驗證',
    'sec_phone_verify': '手機驗證',
    'sec_devices': '登錄設備管理',
    'sec_anti_phishing': '防釣魚碼',
    'status_set': '已設置',
    'status_unset': '未設置',
    'status_bound': '已綁定',
    'status_unbound': '未綁定',
    'cp_title': '修改登錄密碼',
    'cp_old': '原密碼',
    'cp_new': '新密碼 (至少 8 位)',
    'cp_confirm': '確認新密碼',
    'cp_submit': '確認修改',
    'cp_err_mismatch': '兩次輸入的新密碼不一致',
    'cp_err_short': '新密碼至少 8 位',
    'cp_done': '密碼修改成功',
    'pref_general': '通用',
    'pref_language': '語言',
    'pref_currency': '計價貨幣',
    'pref_price_color': '漲跌配色',
    'pref_notify': '通知',
    'pref_notify_market': '行情提醒',
    'pref_notify_notice': '公告推送',
    'color_green_up': '綠漲紅跌',
    'color_red_up': '紅漲綠跌',
    'enabled': '已開啟',
    'disabled': '已關閉',
    'language_select': '選擇語言',
    'news': '資訊',
    'flash': '快訊',
    'notice': '公告',
    'home_tab_overview': '綜合',
    'home_tab_market': '行情',
    'home_tab_terminal': '多維指數',
    'home_tab_liquidation': '多空爆倉',
    'home_tab_whale': '巨鯨雷達',
    'home_tab_funding': '資金費率',
    'invite_recognized': '已識別邀請人, 註冊時將自動填寫邀請碼',
    'friend_request_body': '{name} 請求添加你為好友',
    'view': '查看',
    'peer_default': '對方',
    'login_gate_title': '登錄後使用{name}',
    'login_gate_sub': '終端功能需要驗證身份',
    'go_login': '去登錄',
  };

  // ---------------- English ----------------
  static const Map<String, String> _en = {
    'app_name': 'Mingce',
    'nav_home': 'Home',
    'nav_news': 'News',
    'nav_chat': 'Chat',
    'nav_mine': 'Me',
    'user_center': 'User Center',
    'tab_profile': 'Profile',
    'tab_security': 'Security',
    'tab_preference': 'Preferences',
    'change_avatar_hint': 'Tap to change avatar',
    'nickname': 'Nickname',
    'username': 'Username',
    'email': 'Email',
    'logout': 'Log Out',
    'logout_confirm': 'Chat history stays on this device. You can log in again anytime.',
    'cancel': 'Cancel',
    'save': 'Save',
    'confirm': 'OK',
    'exit': 'Exit',
    'edit_nickname': 'Edit Nickname',
    'nickname_hint': 'Enter a nickname; leave blank to show username',
    'avatar_updated': 'Avatar updated',
    'avatar_too_large': 'Image exceeds 10MB',
    'avatar_upload_failed': 'Avatar upload failed',
    'nickname_updated': 'Nickname updated',
    'update_failed': 'Update failed',
    'coming_soon': 'Coming soon',
    'sec_account': 'Account Security',
    'sec_login_password': 'Login Password',
    'sec_fund_password': 'Fund Password',
    'sec_2fa': 'Google Authenticator (2FA)',
    'sec_device_verify': 'Devices & Verification',
    'sec_email_verify': 'Email Verification',
    'sec_phone_verify': 'Phone Verification',
    'sec_devices': 'Login Devices',
    'sec_anti_phishing': 'Anti-Phishing Code',
    'status_set': 'Set',
    'status_unset': 'Not set',
    'status_bound': 'Bound',
    'status_unbound': 'Not bound',
    'cp_title': 'Change Login Password',
    'cp_old': 'Current password',
    'cp_new': 'New password (min 8 chars)',
    'cp_confirm': 'Confirm new password',
    'cp_submit': 'Confirm',
    'cp_err_mismatch': 'New passwords do not match',
    'cp_err_short': 'New password must be at least 8 characters',
    'cp_done': 'Password changed',
    'pref_general': 'General',
    'pref_language': 'Language',
    'pref_currency': 'Quote Currency',
    'pref_price_color': 'Price Colors',
    'pref_notify': 'Notifications',
    'pref_notify_market': 'Market Alerts',
    'pref_notify_notice': 'Announcements',
    'color_green_up': 'Green up / Red down',
    'color_red_up': 'Red up / Green down',
    'enabled': 'On',
    'disabled': 'Off',
    'language_select': 'Select Language',
    'news': 'News',
    'flash': 'Flash',
    'notice': 'Notice',
    'home_tab_overview': 'Overview',
    'home_tab_market': 'Market',
    'home_tab_terminal': 'Indexes',
    'home_tab_liquidation': 'Liquidations',
    'home_tab_whale': 'Whale Radar',
    'home_tab_funding': 'Funding',
    'invite_recognized': 'Inviter recognized. The invite code will be auto-filled at signup.',
    'friend_request_body': '{name} sent you a friend request',
    'view': 'View',
    'peer_default': 'Peer',
    'login_gate_title': 'Log in to use {name}',
    'login_gate_sub': 'Terminal features require authentication',
    'go_login': 'Log In',
  };

  // ---------------- 日本語 ----------------
  static const Map<String, String> _ja = {
    'app_name': '明策',
    'nav_home': 'ホーム',
    'nav_news': 'ニュース',
    'nav_chat': 'チャット',
    'nav_mine': 'マイページ',
    'user_center': 'ユーザーセンター',
    'tab_profile': 'プロフィール',
    'tab_security': 'セキュリティ',
    'tab_preference': '環境設定',
    'change_avatar_hint': 'タップしてアバターを変更',
    'nickname': 'ニックネーム',
    'username': 'ユーザー名',
    'email': 'メール',
    'logout': 'ログアウト',
    'logout_confirm': 'ログアウト後もチャット履歴は端末に残り、いつでも再ログインできます。',
    'cancel': 'キャンセル',
    'save': '保存',
    'confirm': 'OK',
    'exit': '終了',
    'edit_nickname': 'ニックネームを変更',
    'nickname_hint': 'ニックネームを入力（空欄でユーザー名表示）',
    'avatar_updated': 'アバターを更新しました',
    'avatar_too_large': '画像が10MBを超えています',
    'avatar_upload_failed': 'アバターのアップロードに失敗しました',
    'nickname_updated': 'ニックネームを更新しました',
    'update_failed': '更新に失敗しました',
    'coming_soon': '近日公開予定',
    'sec_account': 'アカウントセキュリティ',
    'sec_login_password': 'ログインパスワード',
    'sec_fund_password': '資金パスワード',
    'sec_2fa': 'Google認証 (2FA)',
    'sec_device_verify': 'デバイスと認証',
    'sec_email_verify': 'メール認証',
    'sec_phone_verify': '電話番号認証',
    'sec_devices': 'ログインデバイス管理',
    'sec_anti_phishing': 'フィッシング対策コード',
    'status_set': '設定済み',
    'status_unset': '未設定',
    'status_bound': '連携済み',
    'status_unbound': '未連携',
    'cp_title': 'ログインパスワード変更',
    'cp_old': '現在のパスワード',
    'cp_new': '新しいパスワード (8文字以上)',
    'cp_confirm': '新しいパスワード確認',
    'cp_submit': '変更する',
    'cp_err_mismatch': '新しいパスワードが一致しません',
    'cp_err_short': '新しいパスワードは8文字以上です',
    'cp_done': 'パスワードを変更しました',
    'pref_general': '一般',
    'pref_language': '言語',
    'pref_currency': '表示通貨',
    'pref_price_color': '騰落配色',
    'pref_notify': '通知',
    'pref_notify_market': '相場アラート',
    'pref_notify_notice': 'お知らせ通知',
    'color_green_up': '緑が上昇 / 赤が下落',
    'color_red_up': '赤が上昇 / 緑が下落',
    'enabled': 'オン',
    'disabled': 'オフ',
    'language_select': '言語を選択',
    'news': 'ニュース',
    'flash': '速報',
    'notice': 'お知らせ',
    'home_tab_overview': '総合',
    'home_tab_market': 'マーケット',
    'home_tab_terminal': '指数',
    'home_tab_liquidation': '清算',
    'home_tab_whale': 'クジラレーダー',
    'home_tab_funding': '金利',
    'invite_recognized': '招待者を認識しました。登録時に招待コードが自動入力されます。',
    'friend_request_body': '{name} から友達リクエストが届きました',
    'view': '見る',
    'peer_default': '相手',
    'login_gate_title': '{name}を使うにはログイン',
    'login_gate_sub': '端末機能には本人確認が必要です',
    'go_login': 'ログイン',
  };

  // ---------------- 한국어 ----------------
  static const Map<String, String> _ko = {
    'app_name': '明策',
    'nav_home': '홈',
    'nav_news': '뉴스',
    'nav_chat': '채팅',
    'nav_mine': '내 정보',
    'user_center': '사용자 센터',
    'tab_profile': '프로필',
    'tab_security': '보안 설정',
    'tab_preference': '환경 설정',
    'change_avatar_hint': '탭하여 아바타 변경',
    'nickname': '닉네임',
    'username': '사용자 이름',
    'email': '이메일',
    'logout': '로그아웃',
    'logout_confirm': '로그아웃 후에도 채팅 기록은 기기에 남으며, 언제든 다시 로그인할 수 있습니다.',
    'cancel': '취소',
    'save': '저장',
    'confirm': '확인',
    'exit': '종료',
    'edit_nickname': '닉네임 변경',
    'nickname_hint': '닉네임 입력 (비워두면 사용자 이름 표시)',
    'avatar_updated': '아바타가 업데이트되었습니다',
    'avatar_too_large': '이미지가 10MB를 초과합니다',
    'avatar_upload_failed': '아바타 업로드 실패',
    'nickname_updated': '닉네임이 업데이트되었습니다',
    'update_failed': '업데이트 실패',
    'coming_soon': '곧 출시 예정',
    'sec_account': '계정 보안',
    'sec_login_password': '로그인 비밀번호',
    'sec_fund_password': '자금 비밀번호',
    'sec_2fa': 'Google 인증 (2FA)',
    'sec_device_verify': '기기 및 인증',
    'sec_email_verify': '이메일 인증',
    'sec_phone_verify': '휴대폰 인증',
    'sec_devices': '로그인 기기 관리',
    'sec_anti_phishing': '피싱 방지 코드',
    'status_set': '설정됨',
    'status_unset': '설정 안 됨',
    'status_bound': '연결됨',
    'status_unbound': '연결 안 됨',
    'cp_title': '로그인 비밀번호 변경',
    'cp_old': '현재 비밀번호',
    'cp_new': '새 비밀번호 (최소 8자)',
    'cp_confirm': '새 비밀번호 확인',
    'cp_submit': '변경하기',
    'cp_err_mismatch': '새 비밀번호가 일치하지 않습니다',
    'cp_err_short': '새 비밀번호는 최소 8자입니다',
    'cp_done': '비밀번호가 변경되었습니다',
    'pref_general': '일반',
    'pref_language': '언어',
    'pref_currency': '표시 통화',
    'pref_price_color': '등락 색상',
    'pref_notify': '알림',
    'pref_notify_market': '시세 알림',
    'pref_notify_notice': '공지 알림',
    'color_green_up': '상승 초록 / 하락 빨강',
    'color_red_up': '상승 빨강 / 하락 초록',
    'enabled': '켜짐',
    'disabled': '꺼짐',
    'language_select': '언어 선택',
    'news': '뉴스',
    'flash': '속보',
    'notice': '공지',
    'home_tab_overview': '종합',
    'home_tab_market': '시세',
    'home_tab_terminal': '지수',
    'home_tab_liquidation': '청산',
    'home_tab_whale': '고래 레이더',
    'home_tab_funding': '펀딩비',
    'invite_recognized': '초대자가 인식되었습니다. 가입 시 초대 코드가 자동 입력됩니다.',
    'friend_request_body': '{name}님이 친구 요청을 본냈습니다',
    'view': '보기',
    'peer_default': '상대방',
    'login_gate_title': '{name}을(를) 사용하려면 로그인',
    'login_gate_sub': '터미널 기능은 본인 인증이 필요합니다',
    'go_login': '로그인',
  };

  // ---------------- Español ----------------
  static const Map<String, String> _es = {
    'app_name': 'Mingce',
    'nav_home': 'Inicio',
    'nav_news': 'Noticias',
    'nav_chat': 'Chat',
    'nav_mine': 'Yo',
    'user_center': 'Centro de usuario',
    'tab_profile': 'Perfil',
    'tab_security': 'Seguridad',
    'tab_preference': 'Preferencias',
    'change_avatar_hint': 'Toca para cambiar el avatar',
    'nickname': 'Apodo',
    'username': 'Usuario',
    'email': 'Correo',
    'logout': 'Cerrar sesión',
    'logout_confirm': 'El historial de chat se conserva en este dispositivo. Puedes volver a entrar cuando quieras.',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'confirm': 'Aceptar',
    'exit': 'Salir',
    'edit_nickname': 'Editar apodo',
    'nickname_hint': 'Introduce un apodo; déjalo vacío para mostrar el usuario',
    'avatar_updated': 'Avatar actualizado',
    'avatar_too_large': 'La imagen supera 10MB',
    'avatar_upload_failed': 'Error al subir el avatar',
    'nickname_updated': 'Apodo actualizado',
    'update_failed': 'Error al actualizar',
    'coming_soon': 'Próximamente',
    'sec_account': 'Seguridad de la cuenta',
    'sec_login_password': 'Contraseña de acceso',
    'sec_fund_password': 'Contraseña de fondos',
    'sec_2fa': 'Google Authenticator (2FA)',
    'sec_device_verify': 'Dispositivos y verificación',
    'sec_email_verify': 'Verificación de correo',
    'sec_phone_verify': 'Verificación de teléfono',
    'sec_devices': 'Dispositivos conectados',
    'sec_anti_phishing': 'Código antiphishing',
    'status_set': 'Configurado',
    'status_unset': 'Sin configurar',
    'status_bound': 'Vinculado',
    'status_unbound': 'Sin vincular',
    'cp_title': 'Cambiar contraseña',
    'cp_old': 'Contraseña actual',
    'cp_new': 'Nueva contraseña (mín. 8 caracteres)',
    'cp_confirm': 'Confirmar contraseña',
    'cp_submit': 'Confirmar',
    'cp_err_mismatch': 'Las contraseñas no coinciden',
    'cp_err_short': 'La contraseña debe tener al menos 8 caracteres',
    'cp_done': 'Contraseña cambiada',
    'pref_general': 'General',
    'pref_language': 'Idioma',
    'pref_currency': 'Moneda de cotización',
    'pref_price_color': 'Colores de precio',
    'pref_notify': 'Notificaciones',
    'pref_notify_market': 'Alertas de mercado',
    'pref_notify_notice': 'Anuncios',
    'color_green_up': 'Verde sube / Rojo baja',
    'color_red_up': 'Rojo sube / Verde baja',
    'enabled': 'Activado',
    'disabled': 'Desactivado',
    'language_select': 'Seleccionar idioma',
    'news': 'Noticias',
    'flash': 'Flash',
    'notice': 'Aviso',
    'home_tab_overview': 'Resumen',
    'home_tab_market': 'Mercado',
    'home_tab_terminal': 'Índices',
    'home_tab_liquidation': 'Liquidaciones',
    'home_tab_whale': 'Radar de ballenas',
    'home_tab_funding': 'Financiación',
    'invite_recognized': 'Invitador reconocido. El código se autocompletará al registrarte.',
    'friend_request_body': '{name} te envió una solicitud de amistad',
    'view': 'Ver',
    'peer_default': 'Contacto',
    'login_gate_title': 'Inicia sesión para usar {name}',
    'login_gate_sub': 'Las funciones del terminal requieren autenticación',
    'go_login': 'Entrar',
  };

  // ---------------- Português ----------------
  static const Map<String, String> _pt = {
    'app_name': 'Mingce',
    'nav_home': 'Início',
    'nav_news': 'Notícias',
    'nav_chat': 'Chat',
    'nav_mine': 'Eu',
    'user_center': 'Centro do usuário',
    'tab_profile': 'Perfil',
    'tab_security': 'Segurança',
    'tab_preference': 'Preferências',
    'change_avatar_hint': 'Toque para alterar o avatar',
    'nickname': 'Apelido',
    'username': 'Usuário',
    'email': 'E-mail',
    'logout': 'Sair',
    'logout_confirm': 'O histórico de chat fica neste dispositivo. Você pode entrar novamente quando quiser.',
    'cancel': 'Cancelar',
    'save': 'Salvar',
    'confirm': 'OK',
    'exit': 'Sair',
    'edit_nickname': 'Editar apelido',
    'nickname_hint': 'Digite um apelido; deixe em branco para mostrar o usuário',
    'avatar_updated': 'Avatar atualizado',
    'avatar_too_large': 'A imagem excede 10MB',
    'avatar_upload_failed': 'Falha ao enviar o avatar',
    'nickname_updated': 'Apelido atualizado',
    'update_failed': 'Falha ao atualizar',
    'coming_soon': 'Em breve',
    'sec_account': 'Segurança da conta',
    'sec_login_password': 'Senha de login',
    'sec_fund_password': 'Senha de fundos',
    'sec_2fa': 'Google Authenticator (2FA)',
    'sec_device_verify': 'Dispositivos e verificação',
    'sec_email_verify': 'Verificação de e-mail',
    'sec_phone_verify': 'Verificação de telefone',
    'sec_devices': 'Dispositivos conectados',
    'sec_anti_phishing': 'Código antiphishing',
    'status_set': 'Definido',
    'status_unset': 'Não definido',
    'status_bound': 'Vinculado',
    'status_unbound': 'Não vinculado',
    'cp_title': 'Alterar senha de login',
    'cp_old': 'Senha atual',
    'cp_new': 'Nova senha (mín. 8 caracteres)',
    'cp_confirm': 'Confirmar nova senha',
    'cp_submit': 'Confirmar',
    'cp_err_mismatch': 'As senhas não coincidem',
    'cp_err_short': 'A senha deve ter pelo menos 8 caracteres',
    'cp_done': 'Senha alterada',
    'pref_general': 'Geral',
    'pref_language': 'Idioma',
    'pref_currency': 'Moeda de cotação',
    'pref_price_color': 'Cores de preço',
    'pref_notify': 'Notificações',
    'pref_notify_market': 'Alertas de mercado',
    'pref_notify_notice': 'Anúncios',
    'color_green_up': 'Verde sobe / Vermelho desce',
    'color_red_up': 'Vermelho sobe / Verde desce',
    'enabled': 'Ativado',
    'disabled': 'Desativado',
    'language_select': 'Selecionar idioma',
    'news': 'Notícias',
    'flash': 'Flash',
    'notice': 'Aviso',
    'home_tab_overview': 'Resumo',
    'home_tab_market': 'Mercado',
    'home_tab_terminal': 'Índices',
    'home_tab_liquidation': 'Liquidações',
    'home_tab_whale': 'Radar de baleias',
    'home_tab_funding': 'Funding',
    'invite_recognized': 'Remetente reconhecido. O código será preenchido no cadastro.',
    'friend_request_body': '{name} enviou um pedido de amizade',
    'view': 'Ver',
    'peer_default': 'Contato',
    'login_gate_title': 'Entre para usar {name}',
    'login_gate_sub': 'Os recursos do terminal exigem autenticação',
    'go_login': 'Entrar',
  };

  // ---------------- हिन्दी ----------------
  static const Map<String, String> _hi = {
    'app_name': 'Mingce',
    'nav_home': 'होम',
    'nav_news': 'समाचार',
    'nav_chat': 'चैट',
    'nav_mine': 'मैं',
    'user_center': 'उपयोगकर्ता केंद्र',
    'tab_profile': 'प्रोफ़ाइल',
    'tab_security': 'सुरक्षा',
    'tab_preference': 'प्राथमिकताएँ',
    'change_avatar_hint': 'अवतार बदलने के लिए टैप करें',
    'nickname': 'उपनाम',
    'username': 'उपयोगकर्ता नाम',
    'email': 'ईमेल',
    'logout': 'लॉग आउट',
    'logout_confirm': 'लॉगआउट के बाद भी चैट इतिहास इस डिवाइस पर रहेगा, आप कभी भी फिर से लॉग इन कर सकते हैं।',
    'cancel': 'रद्द करें',
    'save': 'सहेजें',
    'confirm': 'ठीक',
    'exit': 'बाहर निकलें',
    'edit_nickname': 'उपनाम बदलें',
    'nickname_hint': 'उपनाम दर्ज करें; खाली छोड़ने पर उपयोगकर्ता नाम दिखेगा',
    'avatar_updated': 'अवतार अपडेट हुआ',
    'avatar_too_large': 'छवि 10MB से अधिक है',
    'avatar_upload_failed': 'अवतार अपलोड विफल',
    'nickname_updated': 'उपनाम अपडेट हुआ',
    'update_failed': 'अपडेट विफल',
    'coming_soon': 'जल्द आ रहा है',
    'sec_account': 'खाता सुरक्षा',
    'sec_login_password': 'लॉगिन पासवर्ड',
    'sec_fund_password': 'फंड पासवर्ड',
    'sec_2fa': 'Google प्रमाणक (2FA)',
    'sec_device_verify': 'डिवाइस और सत्यापन',
    'sec_email_verify': 'ईमेल सत्यापन',
    'sec_phone_verify': 'फ़ोन सत्यापन',
    'sec_devices': 'लॉगिन डिवाइस प्रबंधन',
    'sec_anti_phishing': 'एंटी-फ़िशिंग कोड',
    'status_set': 'सेट',
    'status_unset': 'सेट नहीं',
    'status_bound': 'बंधा',
    'status_unbound': 'नहीं बंधा',
    'cp_title': 'लॉगिन पासवर्ड बदलें',
    'cp_old': 'वर्तमान पासवर्ड',
    'cp_new': 'नया पासवर्ड (कम से कम 8 अक्षर)',
    'cp_confirm': 'नया पासवर्ड पुष्टि करें',
    'cp_submit': 'पुष्टि करें',
    'cp_err_mismatch': 'नए पासवर्ड मेल नहीं खाते',
    'cp_err_short': 'नया पासवर्ड कम से कम 8 अक्षर का होना चाहिए',
    'cp_done': 'पासवर्ड बदल गया',
    'pref_general': 'सामान्य',
    'pref_language': 'भाषा',
    'pref_currency': 'कोट मुद्रा',
    'pref_price_color': 'मूल्य रंग',
    'pref_notify': 'सूचनाएँ',
    'pref_notify_market': 'बाज़ार अलर्ट',
    'pref_notify_notice': 'घोषणाएँ',
    'color_green_up': 'हरा ऊपर / लाल नीचे',
    'color_red_up': 'लाल ऊपर / हरा नीचे',
    'enabled': 'चालू',
    'disabled': 'बंद',
    'language_select': 'भाषा चुनें',
    'news': 'समाचार',
    'flash': 'फ़्लैश',
    'notice': 'सूचना',
    'home_tab_overview': 'सारांश',
    'home_tab_market': 'बाज़ार',
    'home_tab_terminal': 'सूचकांक',
    'home_tab_liquidation': 'लिक्विडेशन',
    'home_tab_whale': 'व्हेल राडार',
    'home_tab_funding': 'फंडिंग',
    'invite_recognized': 'निमंत्रक पहचाना गया। साइनअप पर कोड अपने आप भर जाएगा।',
    'friend_request_body': '{name} ने आपको फ्रेंड रिक्वेस्ट भेजी',
    'view': 'देखें',
    'peer_default': 'सामने वाला',
    'login_gate_title': '{name} उपयोग करने के लिए लॉग इन करें',
    'login_gate_sub': 'टर्मिनल सुविधाओं के लिए प्रमाणीकरण आवश्यक है',
    'go_login': 'लॉग इन',
  };
}
